name: Test, Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test || echo "No tests found"
  

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.app_version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Extract App Version
      id: app_version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        mkdir -p ./version-info
        echo "$VERSION" > ./version-info/version.txt

    - name: Upload version as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-version
        path: ./version-info/version.txt
        retention-days: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true        
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-cicd-app:${{ env.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 